# Generated by Django 2.2.5 on 2019-11-07 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
